# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mc_ms_lam_range <- function(M, X, Z, B, mask, num_B_cov, to_add_ID, to_estimate_u, to_estimate_v, niter, rel_tol, to_normalize, is_quiet) {
    .Call('_MCMS_mc_ms_lam_range', PACKAGE = 'MCMS', M, X, Z, B, mask, num_B_cov, to_add_ID, to_estimate_u, to_estimate_v, niter, rel_tol, to_normalize, is_quiet)
}

mc_ms_fit <- function(M, X, Z, B, mask, lambda_L, lambda_H, lambda_b, num_B_cov, to_add_ID, to_estimate_u, to_estimate_v, to_estimate_b, to_estimate_H, niter, rel_tol, to_normalize, is_quiet, post_estimation, impose_null, model_selection_H, model_selection_b) {
    .Call('_MCMS_mc_ms_fit', PACKAGE = 'MCMS', M, X, Z, B, mask, lambda_L, lambda_H, lambda_b, num_B_cov, to_add_ID, to_estimate_u, to_estimate_v, to_estimate_b, to_estimate_H, niter, rel_tol, to_normalize, is_quiet, post_estimation, impose_null, model_selection_H, model_selection_b)
}

mc_ms_cv <- function(M, X, Z, B, mask, num_B_cov, to_add_ID, to_estimate_u, to_estimate_v, to_estimate_b, to_estimate_H, niter, rel_tol, to_normalize, cv_ratio, num_folds, n_config, cube_search, is_quiet, post_estimation, impose_null, model_selection_H, model_selection_b, return_mse, return_1se, seed) {
    .Call('_MCMS_mc_ms_cv', PACKAGE = 'MCMS', M, X, Z, B, mask, num_B_cov, to_add_ID, to_estimate_u, to_estimate_v, to_estimate_b, to_estimate_H, niter, rel_tol, to_normalize, cv_ratio, num_folds, n_config, cube_search, is_quiet, post_estimation, impose_null, model_selection_H, model_selection_b, return_mse, return_1se, seed)
}

mc_ms_lambda_analysis <- function(M, X, Z, B, mask, file_path, num_B_cov, to_normalize, to_estimate_u, to_estimate_v, to_estimate_b, to_estimate_H, to_add_ID, niter, n_config, rel_tol, is_quiet, n_lambda, cv_ratio, num_folds, cube_search, post_estimation, impose_null, model_selection_H, model_selection_b, seed, write_to_file, iter_lambda) {
    .Call('_MCMS_mc_ms_lambda_analysis', PACKAGE = 'MCMS', M, X, Z, B, mask, file_path, num_B_cov, to_normalize, to_estimate_u, to_estimate_v, to_estimate_b, to_estimate_H, to_add_ID, niter, n_config, rel_tol, is_quiet, n_lambda, cv_ratio, num_folds, cube_search, post_estimation, impose_null, model_selection_H, model_selection_b, seed, write_to_file, iter_lambda)
}

